name: Release

on:
    push:
        tags:
            - "*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install bun
              run: npm install -g bun

            - name: Run bun install --post
              run: bun install --post

            - name: Run bun run build
              run: bun run build

            - name: Package dist folder into a .zip
              run: |
                  zip -r dist.zip dist/

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "dist.zip"
                  token: ${{ secrets.GITHUB_TOKEN }}
